dist: trusty
sudo: required
language: python
matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=lint

install:
  - pip install -r requirements-dev.txt

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - python setup.py test
  - python setup.py coverage

after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          python setup.py coverage && codecov
        fi
      fi
